# Change these first
owner: 7ednet # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Toots Social
    url: https://toots.social
  - name: Toots Social's static things
    url: https://s3.toots.social
  - name: @im.sb Mastodon
    url: https://mastodon.im.sb
  - name: @im.sb Mastodon's static things
    url: https://s3.imsb.app

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.7ed.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontents.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "7ED Services status."
  introMessage: Welcome to uptime page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
